### ISSUE TITLE
No space to provide login credentials 

### ISSUE THREAD

**Issue by Birchell** [scryptedapp/arlo#15]
![image](https://github.com/scryptedapp/arlo/assets/121697227/5273a3d0-8c77-4493-b9ec-0827c2b4cf20)

downloaded the arlo plugin for scrypted but cant see any place for my login and 2fa credentials, im new to scrypted but have connected my home assistant instance and assume this should be relatively similar

**Comment by bjia56** [comment]
Most likely the plugin failed to load. What host OS, and which install method did you use to install scrypted?

Can also click on the Console and reload the plugin to see what the error is

**Comment by Birchell** [comment]
![image](https://github.com/scryptedapp/arlo/assets/121697227/92200d7d-18b2-46ff-a90d-00371bcfab5f)

not seeing much in console but im getting error events.
really not sure what im missing sorry for the rookie post

![image](https://github.com/scryptedapp/arlo/assets/121697227/ed895516-9d66-4d01-a13f-94f66747b012)

**Comment by Birchell** [comment]
> Most likely the plugin failed to load. What host OS, and which install method did you use to install scrypted?
> 
> Can also click on the Console and reload the plugin to see what the error is

im running scrypted on a win 11 PC thru the desktop app.

**Comment by bjia56** [comment]
@Birchell most likely you need to install Python, it's recommended to use 3.11 (not 3.12)

**Comment by bjia56** [comment]
Actually, 3.10 may be better if you're using the NVR desktop app
